import DialogLayout from "../../layouts/DialogLayout";
import FlowButton from "../common/FlowButton";
import { useStyles } from "./styles";
import "../../../assets/styles/components/flowDialog.scss";
import "../../../assets/styles/common.scss";
import docImg from "../../../assets/images/icons/doc.svg";
import calendarImg from "../../../assets/images/icons/calendar.svg";
import fromtoImg from "../../../assets/images/icons/from_to.svg";
import houseImg from "../../../assets/images/icons/houses.svg";
import processingImg from "../../../assets/images/icons/processing.svg";
import documentsImg from "../../../assets/images/icons/documents.svg";
import reportImg from "../../../assets/images/icons/report.svg";
import locationImg from "../../../assets/images/icons/location_marker.svg";
import formImg from "../../../assets/images/icons/form.svg";
import performaInvoiceImg from "../../../assets/images/icons/performa_invoice.svg";
import transporterTruckImg from "../../../assets/images/icons/transporter_truck.svg";
import vehicleInfoImg from "../../../assets/images/icons/vehicle_info.svg";
import cargoInfoImg from "../../../assets/images/icons/cargo_info.svg";
import "../../../assets/styles/components/flowDialog.scss";
import CargoEvidence from "./CargoEvidence";
import DocPanel from "../common/DocPanel";
import PackageDetail from "../common/PackageDetail";

const DialogTitle = ({ handleContinue }) => {
  const classes = useStyles();
  return (
    <div className={classes.submit_title_container}>
      <h1
        className={`${classes.submit_title} ${classes.pointer}`}
        onClick={() => handleContinue("addpackage")}
      >
        Add Package
      </h1>
      <FlowButton text="Submit" onClick={handleContinue} />
    </div>
  );
};
const SubmitPackageDialog = ({ open, handleClose, handleContinue }) => {
  const classes = useStyles();
  return (
    <DialogLayout
      open={open}
      handleClose={handleClose}
      handleContinue={null}
      title={<DialogTitle handleContinue={handleContinue} />}
      showArrow={true}
    >
      <div
        className={`${classes.dialog_content_wrapper} dialog_submit_package_container`}
      >
        <div className="upper_panel">
          <div className="child">
            <div className="child_header">
              <img src={docImg} alt="doc icon" />
              <h1>E-Way Bill Number - 8976 4567 3456</h1>
            </div>
            <div className="destination_container">
              <div className="destination">
                <div className="from_to">
                  <span>From</span>
                  <span>To</span>
                </div>
                <div className="location_img_container">
                  <img src={fromtoImg} alt="location img" />
                </div>
                <div className="location_name">
                  <h1>Kerwan Refinery Center, Iran</h1>
                  <h1>Dehli Petrocheimcals ltd, Delhi</h1>
                </div>
              </div>
            </div>
          </div>
          <div className="child">
            <div className="child_header">
              <img src={calendarImg} alt="calendar icon" />
              <h1>Valid Date</h1>
            </div>
            <div className="destination_container">
              <div className="destination">
                <div className="from_to">
                  <span>From</span>
                  <span>To</span>
                </div>
                <div className="location_name">
                  <h1>22nd March 2022 09:18 PM</h1>
                  <h1>23rd April 2022</h1>
                </div>
              </div>
            </div>
          </div>
          <div className="child">
            <div className="child_header">
              <img src={houseImg} alt="house icon" />
              <h1>Generated by</h1>
            </div>
            <div className="destination_container">
              <div className="destination">
                <div className="from_to">
                  <span>From</span>
                  <span>To</span>
                </div>
                <div className="location_name">
                  <h1>Ram Enterprises</h1>
                  <h1>234516</h1>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="middle_panel">
          <div className="child">
            <PackageDetail
              icon={transporterTruckImg}
              header={"Transporter info"}
            >
              <div>
                <h1>Transporter:</h1>
              </div>
            </PackageDetail>
            <PackageDetail icon={vehicleInfoImg} header={"Vehicle info"}>
              <div>
                <h1>Transporter:</h1>
                <h1>
                  Vehicle Health: <span className="green_txt">90%</span>
                </h1>
              </div>
            </PackageDetail>
            <PackageDetail icon={cargoInfoImg} header={"Cargo info"}>
              <div>
                <h1>
                  Category of cargo: <span>Chemical Materials</span>
                </h1>
                <h1>
                  Total Weight of cargo: <span>4 Gallons</span>
                </h1>
                <h1>
                  Contents of cargo: <span>Petroleum Product</span>
                </h1>
              </div>
            </PackageDetail>
          </div>
          <div className="child">
            <div className="child_header">
              <img src={documentsImg} alt="documents icon" />
              <div className="content">
                <h1>Generated Documents</h1>
                <div className="child_content">
                  <div className="left_side">
                    <DocPanel text={"Quality Check Report"} icon={reportImg} />
                    <DocPanel
                      text={"Certificate of origin"}
                      icon={locationImg}
                    />
                    <DocPanel
                      text={"Proforma Invoice"}
                      icon={performaInvoiceImg}
                    />
                  </div>
                  <div className="left_side">
                    <DocPanel text={"Declaration Form"} icon={formImg} />
                    <DocPanel text={"Bill of lading"} icon={formImg} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="lower_panel">
          <h1>Evidences of Cargo</h1>
          <CargoEvidence
            title="Processing"
            icon={processingImg}
            images={[
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
            ]}
          />
          <CargoEvidence
            title="Safety"
            icon={processingImg}
            images={[
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
            ]}
          />
          <CargoEvidence
            title="Scanning"
            icon={processingImg}
            images={[
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
            ]}
          />
          <CargoEvidence
            title="Packing"
            icon={processingImg}
            images={[
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
            ]}
          />
          <CargoEvidence
            title="Loading"
            icon={processingImg}
            images={[
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
              "https://source.unsplash.com/user/c_v_r",
            ]}
          />

          <div className="package_submit_btn">
            <FlowButton text={"Submit"} onClick={handleContinue} />
          </div>
        </div>
      </div>
    </DialogLayout>
  );
};

export default SubmitPackageDialog;
